# Generated by Django 5.2.17 on 2026-09-28 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='homepage/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('image_alt', models.CharField(max_length=250)),
                ('static_image', models.CharField(blank=True, help_text='Bundled image basename, without extension.', max_length=160)),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('attribution_verified', models.BooleanField(default=False, help_text='Confirm NCCT delivery and image rights before publishing as a completed project.')),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
