# Generated by Django 5.2.17 on 2026-10-03 02:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models



def populate_slugs(apps, schema_editor):
    from django.utils.text import slugify
    Model = apps.get_model('projects', 'Project')
    for obj in Model.objects.all().iterator():
        obj.slug = (slugify(obj.title)[:150] or 'item') + '-' + str(obj.pk)
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contentpage_homepage_bing_verification_and_more"),
        ("products", "0002_category_canonical_url_category_published_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="applications",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="core.application"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Optional canonical override. Normally leave blank.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(
                blank=True,
                help_text="Only publicly verified client names.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="published",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="scope",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="seo_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="project",
            name="seo_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="homepage/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "avif"]
                            )
                        ],
                    ),
                ),
                ("image_alt", models.CharField(max_length=250)),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Bundled image basename, without extension.",
                        max_length=160,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(model_name='project', name='slug', field=models.SlugField(blank=True, max_length=180, unique=True)),
    ]
