# Generated by Django 5.2.17 on 2026-10-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_applications_project_canonical_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="caption",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
