# Generated by Django 5.2.17 on 2026-10-05 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_catalogue_admin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Tick only for pages that should not appear in Google. Also removes the page from the sitemap.",
                verbose_name="Hide from search engines",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search description.",
                max_length=300,
                verbose_name="Social share description",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional. 1200x630 px works best. Defaults to the main image.",
                upload_to="social/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Social share image",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search title.",
                max_length=100,
                verbose_name="Social share title",
            ),
        ),
    ]
