# Generated by Django 5.2.17 on 2026-09-28 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='homepage/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('image_alt', models.CharField(max_length=250)),
                ('static_image', models.CharField(blank=True, help_text='Bundled image basename, without extension.', max_length=160)),
                ('hero_heading', models.CharField(default='Light that\nshapes space.', max_length=100)),
                ('hero_copy', models.CharField(default='Architectural and professional lighting.\nFor the spaces we live, work and move through.', max_length=240)),
                ('hero_caption', models.CharField(default='Architectural lighting · NCCT image library', max_length=180)),
                ('introduction_heading', models.CharField(default='Engineering light.\nElevating spaces.', max_length=100)),
                ('introduction', models.TextField(default='NCCT brings LED lighting into architecture — indoors, outdoors and across decorative, industrial and professional applications. Light that serves a purpose and gives a space its character.')),
                ('email', models.EmailField(default='info@ncctdxb.com', max_length=254)),
                ('phone', models.CharField(default='+971 58 1310300', max_length=32)),
                ('address', models.CharField(default='Office 2202, Ubora Tower, Al Abraj Street, Business Bay, Dubai, UAE', max_length=200)),
                ('privacy_text', models.TextField(blank=True, help_text='Approved privacy notice. Leave blank until supplied.')),
                ('terms_text', models.TextField(blank=True)),
                ('cookie_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifiedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('source', models.URLField(help_text='Evidence supporting this number.')),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
