# Generated by Django 5.2.17 on 2026-10-03 02:50

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_homepageseedstate"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("published", models.BooleanField(db_index=True, default=True)),
                ("seo_title", models.CharField(blank=True, max_length=100)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional canonical override. Normally leave blank.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("introduction", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="homepage",
            name="bing_verification",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="homepage",
            name="company_name",
            field=models.CharField(default="NCCT", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_heading",
            field=models.CharField(
                default="Let's bring your space to light.", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer_description",
            field=models.CharField(
                default="Architectural & professional lighting. Dubai, United Arab Emirates.",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="google_verification",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="homepage",
            name="logo",
            field=models.ImageField(
                blank=True,
                upload_to="company/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "webp", "jpg"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="products_heading",
            field=models.CharField(
                default="The detail makes the difference.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="projects_heading",
            field=models.CharField(default="Spaces, brought to light.", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_description",
            field=models.CharField(
                default="Explore NCCT indoor, outdoor, decorative, industrial and professional lighting. Based in Business Bay, Dubai.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_title",
            field=models.CharField(
                default="NCCT — Architectural & Professional Lighting", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_capabilities",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_products",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_projects",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_solutions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="solutions_heading",
            field=models.CharField(
                default="The right light. For every setting.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_caption",
            field=models.CharField(
                default="Architectural lighting · NCCT image library", max_length=180
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="introduction",
            field=models.TextField(
                default="NCCT brings LED lighting into architecture — indoors, outdoors and across decorative, industrial and professional applications. Light that serves a purpose and gives a space its character."
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="homepage/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "avif"]
                            )
                        ],
                    ),
                ),
                ("image_alt", models.CharField(max_length=250)),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Bundled image basename, without extension.",
                        max_length=160,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("published", models.BooleanField(db_index=True, default=True)),
                ("seo_title", models.CharField(blank=True, max_length=100)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional canonical override. Normally leave blank.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("source_url", models.URLField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="products.category"),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("published", models.BooleanField(db_index=True, default=True)),
                ("seo_title", models.CharField(blank=True, max_length=100)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional canonical override. Normally leave blank.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("datasheet", "Technical datasheet"),
                            ("catalogue", "Catalogue"),
                            ("brochure", "Brochure"),
                            ("installation", "Installation guide"),
                            ("certificate", "Certificate"),
                            ("company", "Company profile"),
                        ],
                        default="datasheet",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="documents/%Y/%m/",
                        validators=[core.validators.validate_pdf],
                    ),
                ),
                (
                    "bundled_file",
                    models.CharField(
                        blank=True,
                        help_text="Bundled PDF filename under static/documents; leave blank for uploads.",
                        max_length=180,
                    ),
                ),
                ("file_size", models.PositiveIntegerField(default=0, editable=False)),
                ("language", models.CharField(default="English", max_length=40)),
                ("source_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="products.product"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
