# Generated by Django 5.2.17 on 2026-10-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contentpage_homepage_bing_verification_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capability",
            options={
                "ordering": ["order", "pk"],
                "verbose_name_plural": "capabilities",
            },
        ),
    ]
