# Generated by Django 5.2.17 on 2026-10-05 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_capability_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional hero image. Leave blank to use the bundled image.",
                upload_to="pages/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "avif"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="image_alt",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
