# Generated by Django 5.2.17 on 2026-10-05 08:18

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_catalogue_admin_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("products", "Products page"),
                            ("projects", "Projects page"),
                            ("resources", "Resources page"),
                            ("solutions", "Solutions page"),
                            ("contact", "Contact page"),
                            ("about", "About page (call to action)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=100)),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="The main page heading (H1).",
                        max_length=150,
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                (
                    "notice",
                    models.TextField(
                        blank=True,
                        help_text="Small print shown on the page (Projects page).",
                        verbose_name="Notice / disclosure",
                    ),
                ),
                (
                    "cta_eyebrow",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Call-to-action label"
                    ),
                ),
                (
                    "cta_heading",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Call-to-action heading",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Call-to-action button text",
                    ),
                ),
                (
                    "cta_link",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to open the enquiry form.",
                        max_length=200,
                        validators=[core.validators.validate_link],
                        verbose_name="Call-to-action link",
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=100)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Social share title"
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Social share description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        upload_to="social/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                        verbose_name="Social share image",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False, verbose_name="Hide from search engines"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "page text & SEO",
                "verbose_name_plural": "page text & SEO",
                "ordering": ["key"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Tick only for pages that should not appear in Google. Also removes the page from the sitemap.",
                verbose_name="Hide from search engines",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search description.",
                max_length=300,
                verbose_name="Social share description",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional. 1200x630 px works best. Defaults to the main image.",
                upload_to="social/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Social share image",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search title.",
                max_length=100,
                verbose_name="Social share title",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Tick only for pages that should not appear in Google. Also removes the page from the sitemap.",
                verbose_name="Hide from search engines",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search description.",
                max_length=300,
                verbose_name="Social share description",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional. 1200x630 px works best. Defaults to the main image.",
                upload_to="social/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Social share image",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search title.",
                max_length=100,
                verbose_name="Social share title",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="ga4_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="Optional, e.g. G-XXXXXXXXXX. Only loads once the site is live and indexable.",
                max_length=20,
                validators=[core.validators.validate_ga4],
                verbose_name="Google Analytics (GA4) ID",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_link",
            field=models.CharField(
                default="/projects/",
                max_length=200,
                validators=[core.validators.validate_link],
                verbose_name="Primary button link",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(
                default="Explore projects",
                max_length=40,
                verbose_name="Primary button text",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_eyebrow",
            field=models.CharField(
                default="Architectural & professional lighting", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_secondary_link",
            field=models.CharField(
                default="#solutions",
                max_length=200,
                validators=[core.validators.validate_link],
                verbose_name="Secondary link",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_secondary_text",
            field=models.CharField(
                default="Discover solutions",
                max_length=40,
                verbose_name="Secondary link text",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Default image shown when links are shared. Defaults to the hero image.",
                upload_to="social/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Social share image",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Optional thumbnail for the document.",
                upload_to="resources/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Cover / thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="cover_alt",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="resource",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Tick only for pages that should not appear in Google. Also removes the page from the sitemap.",
                verbose_name="Hide from search engines",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search description.",
                max_length=300,
                verbose_name="Social share description",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional. 1200x630 px works best. Defaults to the main image.",
                upload_to="social/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Social share image",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Defaults to the search title.",
                max_length=100,
                verbose_name="Social share title",
            ),
        ),
    ]
