# Generated by Django 5.2.17 on 2026-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('project_type', models.CharField(blank=True, choices=[('Commercial', 'Commercial'), ('Hospitality', 'Hospitality'), ('Residential', 'Residential'), ('Retail', 'Retail'), ('Infrastructure', 'Infrastructure'), ('Industrial', 'Industrial'), ('Government/Public Sector', 'Government/Public Sector'), ('Other', 'Other')], max_length=30)),
                ('message', models.TextField(blank=True, max_length=4000)),
                ('consent', models.BooleanField()),
                ('consent_text', models.CharField(default='I agree to be contacted regarding this enquiry.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('source_page', models.CharField(default='/', max_length=100)),
                ('submission_id', models.UUIDField(editable=False, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
