# Generated by Django 5.2.17 on 2026-10-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enquiry",
            options={"ordering": ["-created_at"], "verbose_name_plural": "enquiries"},
        ),
    ]
