# Generated by Django 5.2.17 on 2026-09-28 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='homepage/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('image_alt', models.CharField(max_length=250)),
                ('static_image', models.CharField(blank=True, help_text='Bundled image basename, without extension.', max_length=160)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('source_url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='homepage/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('image_alt', models.CharField(max_length=250)),
                ('static_image', models.CharField(blank=True, help_text='Bundled image basename, without extension.', max_length=160)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.CharField(blank=True, help_text='Verified specifications only.', max_length=180)),
                ('source_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
