# Generated by Django 5.2.17 on 2026-10-03 02:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models



def populate_slugs(apps, schema_editor):
    from django.utils.text import slugify
    Model = apps.get_model('products', 'Category')
    for obj in Model.objects.all().iterator():
        obj.slug = (slugify(obj.name)[:150] or 'item') + '-' + str(obj.pk)
        obj.save(update_fields=['slug'])
    Model = apps.get_model('products', 'Product')
    for obj in Model.objects.all().iterator():
        obj.slug = (slugify(obj.name)[:150] or 'item') + '-' + str(obj.pk)
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contentpage_homepage_bing_verification_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Optional canonical override. Normally leave blank.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="published",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="applications",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="core.application"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Optional canonical override. Normally leave blank.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="colour_temperature",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="full_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ip_rating",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="product",
            name="model_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="mounting_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=250)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="homepage/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "avif"]
                            )
                        ],
                    ),
                ),
                ("image_alt", models.CharField(max_length=250)),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Bundled image basename, without extension.",
                        max_length=160,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=250)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_rows",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "label"), name="unique_product_spec_label"
                    )
                ],
            },
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(model_name='category', name='slug', field=models.SlugField(blank=True, max_length=180, unique=True)),
        migrations.AlterField(model_name='product', name='slug', field=models.SlugField(blank=True, max_length=180, unique=True)),
    ]
