# Generated by Django 5.2.17 on 2026-10-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_canonical_url_category_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="caption",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="category",
            name="source_url",
            field=models.URLField(blank=True),
        ),
    ]
